"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { read } from "@/lib/contract";
import { CONTRACT_ADDRESS, EXPLORER } from "@/lib/config";

export default function Home(){
 const [stats,setStats]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{read("get_stats").then(setStats).catch((e:any)=>setError(e?.message||"Studionet read unavailable"))},[]);
 const fmt=(x:any)=>x===undefined?"-":String(x);
 return <>
  <section className="landing-hero"><div className="hero-copy"><div className="kicker">CONSENSUS BEFORE RISK · CONSENSUS AFTER FAILURE</div><h1>Don’t Promise<br/>What You Can’t Serve.</h1><p>HEADROOM makes service commitments pass mechanical headroom gates and live semantic review before exposure. If a miss occurs, the same frozen covenant governs the facts and the contract calculates settlement.</p><div className="hero-actions"><Link className="button primary" href="/control">Enter Control Room</Link><Link className="button orange" href="/services/new">Bond a Service</Link></div><span className="network-tag">GENLAYER STUDIONET · CHAIN 61999</span></div>
   <div className="admission-console"><div className="console-top"><span>HEADROOM / PROMISE ENVELOPE</span><span className="signal">{stats?"LIVE PROTOCOL STATE":"AWAITING READ"}</span></div><div className="instrument-label">Capacity &amp; bonded liability are checked before semantic admission.</div><div className="gauge"><div className="gauge-head"><span>Covenants</span><b>{fmt(stats?.covenants)}</b></div><div className="meter"><i style={{width:stats?"100%":"0%"}}/></div></div><div className="instrument-grid"><div><span>ADMISSIONS</span><b>{fmt(stats?.admissions)}</b></div><div><span>PREVENTED</span><b>{fmt(stats?.prevented)}</b></div><div><span>SETTLEMENTS</span><b>{fmt(stats?.settlements)}</b></div><div><span>ACCOUNTING</span><b className={stats?.accounting_balanced?"lime":"ice"}>{stats?stats.accounting_balanced?"BALANCED":"CHECK":"-"}</b></div></div>{error&&<p className="micro-note">On-chain state unavailable: {error}</p>}</div>
  </section>
  <section className="landing-section split-section"><div><div className="kicker">THE PROTOCOL THESIS</div><h2>The Same Covenant Governs Formation And Failure.</h2><p>HEADROOM controls whether a risky promise exists in the first place. If prevention fails, the original evidence and exception rules become the law for the incident.</p></div><div className="dual-flow"><Process title="BEFORE RISK" tone="before" items={["Provider Bonds","Covenant Freezes Rules","Mechanical Headroom","GenLayer Admission","Active SLA"]}/><Process title="AFTER FAILURE" tone="after" items={["Independent Measurement","Frozen Exception","Incident Facts","Deterministic Liability","GEN Settlement"]}/></div></section>
  <section className="landing-section"><div className="section-heading"><div><div className="kicker">DETERMINISTIC ENVELOPE</div><h2>The Promise Surface</h2></div><p>Code decides what can be counted. Consensus is reserved for evidence that needs judgment.</p></div><div className="promise-surface"><div className="surface-head"><span>CAPACITY ENVELOPE</span><span>MECHANICAL GATE / ALWAYS DETERMINISTIC</span></div><div className="surface-rows"><div><span>Capacity ceiling</span><b>Frozen covenant limit</b></div><div><span>Safe reserve</span><b>Minimum headroom protected</b></div><div><span>Already committed</span><b>Active obligations only</b></div><div className="incoming"><span>Incoming request</span><b>Tested before review</b></div><div className="after-row"><span>Post-admission headroom</span><b>Rechecked at activation</b></div></div><div className="surface-foot"><span>PROVIDER BOND</span><strong>Reserved liability + incoming maximum credit ≤ bonded GEN</strong><span>NO COLLATERAL · NO PROMISE</span></div></div></section>
  <section className="landing-section"><div className="section-heading"><div><div className="kicker">WHAT HEADROOM PREVENTS</div><h2>Risk Is Stopped At Its Source.</h2></div></div><div className="prevention-board"><article><span>01 / OVERBOOKING</span><h3>Capacity outruns delivery</h3><p>Normal failure: commitments stack past the protected operating envelope.</p><b>HEADROOM rejects requests above deterministic safe capacity before consensus.</b></article><article><span>02 / UNCOVERED LIABILITY</span><h3>Credit without collateral</h3><p>Normal failure: a provider makes more SLA exposure than its bond can cover.</p><b>HEADROOM requires bond headroom before admission becomes reviewable.</b></article><article><span>03 / RETROACTIVE CHANGE</span><h3>Maintenance written after the fact</h3><p>Normal failure: operational changes are recast as exceptions after an outage.</p><b>HEADROOM only protects a change that passes review before its window begins.</b></article><article><span>04 / SELF-SERVING EXCEPTION</span><h3>One party writes the incident story</h3><p>Normal failure: provider or customer controls the facts that trigger payment.</p><b>GenLayer checks evidence; frozen covenant rules and code govern consequences.</b></article></div></section>
  <section className="landing-section lifecycle-section"><div className="section-heading"><div><div className="kicker">ONE BONDED LIFECYCLE</div><h2>From Promise To Settlement.</h2></div><Link className="text-link" href="/protocol">Explore the protocol ↗</Link></div><div className="lifecycle-rail">{[["FORMATION","Bond covenant","create_covenant"],["ADMISSION","Request · gate · consensus","request_reservation · review_reservation"],["OPERATIONS","Preflight the change","propose_change · review_change"],["INCIDENT","Measure · examine · challenge","open_incident · examine_incident"],["SETTLEMENT","Calculate · finalize · withdraw","judge_liability · finalize_incident · withdraw_credit"]].map(([n,t,m],i)=><div className="lifecycle-step" key={n}><span>0{i+1} / {n}</span><b>{t}</b><code>{m}</code></div>)}</div></section>
  <section className="landing-section consensus-section"><div><div className="kicker">WHY GENLAYER</div><h2>Facts Need Consensus.<br/>Money Needs Rules.</h2><p>A deterministic contract can compare timestamps and calculate overlap. It cannot independently decide whether changing public evidence actually proves a service was healthy, whether a dependency caused impact, or whether an exception clause applies.</p></div><div className="facts-money"><div><span>GENLAYER ESTABLISHES</span><b>Service health · measurement validity · causation · clause satisfaction · evidence conflicts</b></div><div className="transfer">FACTS → CONTRACT LAW</div><div><span>CONTRACT CODE CALCULATES</span><b>Capacity · collateral · temporal overlap · liable BPS · payout · escrow accounting</b></div></div></section>
  <section className="landing-section evidence-section"><div className="section-heading"><div><div className="kicker">FROZEN AT COVENANT FORMATION</div><h2>Origin + Authorized Class = Evidence Candidate</h2></div></div><div className="evidence-model"><article className="evidence-stage"><span className="evidence-stage-number">01</span><h3>Register Origin</h3><p>HTTPS origin is frozen. Future paths may vary.</p></article><article className="evidence-stage"><span className="evidence-stage-number">02</span><h3>Authorize Class</h3><p>An origin may submit only its frozen evidence class.</p></article><article className="evidence-stage"><span className="evidence-stage-number">03</span><h3>Preserve Independence</h3><p>Duplicate origins do not count twice. A provider origin cannot impersonate an independent probe.</p></article><article className="evidence-stage"><span className="evidence-stage-number">04</span><h3>Consensus Reads Content</h3><p>Validators evaluate permitted evidence. Redirect provenance is not claimed when the runtime cannot expose it.</p></article></div></section>
  <section className="landing-section release-section"><div><div className="kicker">CANONICAL RELEASE</div><h2>Live On-Chain State</h2><p>Network: GenLayer Studionet · Chain 61999</p><p>Contract: <code>{CONTRACT_ADDRESS||"Not configured"}</code></p><p>Source: <code>add2f35d08cde554bec6d9bed98c5094554035d9</code></p><p>Accounting: <b>{stats?String(stats.accounting_balanced):"Read unavailable"}</b></p></div><a className="button ghost" href={CONTRACT_ADDRESS?`${EXPLORER}/address/${CONTRACT_ADDRESS}`:undefined}>View on Explorer ↗</a></section>
  <section className="final-cta"><div className="kicker">CONTROL THE EXPOSURE</div><h2>Control The Promise<br/>Before The Promise Controls You.</h2><div className="final-cta-actions"><Link className="button primary" href="/control">Enter Control Room</Link><Link className="button orange" href="/services/new">Bond a Service</Link><Link className="button ghost" href="/protocol">Read the Protocol</Link></div></section>
 </>;
 }
function Process({title,tone,items}:{title:string,tone:string,items:string[]}){return <div className={`flow-side ${tone}`}><span>{title}</span><div className="flow-stages">{items.map((item,i)=><div className="flow-stage" key={item}><b>0{i+1}</b><strong>{item}</strong></div>)}</div></div>}


