"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { read } from "@/lib/contract";
import { CONTRACT_ADDRESS, EXPLORER } from "@/lib/config";

export default function Home(){
 const [stats,setStats]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{read("get_stats").then(setStats).catch((e:any)=>setError(e?.message||"Studionet read unavailable"))},[]);
 const fmt=(x:any)=>x===undefined?"-":String(x);
 return <>
  <section className="landing-hero"><div className="hero-copy"><div className="kicker">CONSENSUS BEFORE RISK · CONSENSUS AFTER FAILURE</div><h1>Donâ€™t Promise<br/>What You Canâ€™t Serve.</h1><p>HEADROOM makes service commitments pass mechanical headroom gates and live semantic review before exposure. If a miss occurs, the same frozen covenant governs the facts and the contract calculates settlement.</p><div className="hero-actions"><Link className="button primary" href="/control">Enter Control Room</Link><Link className="button orange" href="/services/new">Bond a Service</Link></div><span className="network-tag">GENLAYER STUDIONET · CHAIN 61999</span></div>
   <div className="admission-console"><div className="console-top"><span>HEADROOM / PROMISE ENVELOPE</span><span className="signal">{stats?"LIVE PROTOCOL STATE":"AWAITING READ"}</span></div><div className="instrument-label">Capacity &amp; bonded liability are checked before semantic admission.</div><div className="gauge"><div className="gauge-head"><span>Covenants</span><b>{fmt(stats?.covenants)}</b></div><div className="meter"><i style={{width:stats?"100%":"0%"}}/></div></div><div className="instrument-grid"><div><span>ADMISSIONS</span><b>{fmt(stats?.admissions)}</b></div><div><span>PREVENTED</span><b>{fmt(stats?.prevented)}</b></div><div><span>SETTLEMENTS</span><b>{fmt(stats?.settlements)}</b></div><div><span>ACCOUNTING</span><b className={stats?.accounting_balanced?"lime":"ice"}>{stats?stats.accounting_balanced?"BALANCED":"CHECK":"-"}</b></div></div>{error&&<p className="micro-note">On-chain state unavailable: {error}</p>}</div>
  </section>
  <section className="landing-section split-section"><div><div className="kicker">THE PROTOCOL THESIS</div><h2>The Same Covenant Governs Formation And Failure.</h2><p>HEADROOM controls whether a risky promise exists in the first place. If prevention fails, the original evidence and exception rules become the law for the incident.</p></div><div className="dual-flow"><Process title="BEFORE RISK" tone="before" items={["Provider Bonds","Covenant Freezes Rules","Mechanical Headroom","GenLayer Admission","Active SLA"]}/><Process title="AFTER FAILURE" tone="after" items={["Independent Measurement","Frozen Exception","Incident Facts","Deterministic Liability","GEN Settlement"]}/></div></section>
  <section className="landing-section"><div className="section-heading"><div><div className="kicker">DETERMINISTIC ENVELOPE</div><h2>The Promise Surface</h2></div><p>Illustrative Mechanics. Code decides what can be counted before consensus.</p></div><div className="instrument-surfaces"><Instrument title="CAPACITY ENVELOPE" rows={[["Capacity Ceiling","100% envelope"],["Protected Safe Reserve","20% held back"],["Already Committed","58% reserved"],["Incoming Request","30% requested"],["Post-Admission Headroom","12% remaining"]]}/><Instrument title="LIABILITY ENVELOPE" rows={[["Provider Bond","100 GEN bonded"],["Reserved Liability","62 GEN held"],["Incoming Maximum Credit","45 GEN requested"],["Remaining Bond Headroom","38 GEN available"]]}/></div><div className="instrument-law"><b>NO COLLATERAL, NO PROMISE</b><span>Deterministic denial ends the request before semantic admission.</span></div></section>
  <section className="landing-section"><div className="section-heading"><div><div className="kicker">WHAT HEADROOM PREVENTS</div><h2>Risk Is Stopped At Its Source.</h2></div></div><div className="prevention-board"><article><span>01 / OVERBOOKING</span><h3>Capacity outruns delivery</h3><div className="mechanism-diagram"><div className="diagram-rail"><i/><b/></div><small>Incoming crosses safe ceiling</small></div><p>Requests above deterministic safe capacity stop before consensus.</p></article><article><span>02 / UNCOVERED LIABILITY</span><h3>Credit without collateral</h3><div className="mechanism-diagram"><div className="diagram-rail liability"><i/><b/></div><small>Maximum credit exceeds free collateral</small></div><p>Bond headroom must cover every admitted exposure.</p></article><article><span>03 / RETROACTIVE CHANGE</span><h3>Maintenance written after the fact</h3><div className="mechanism-diagram timeline"><b>Notice</b><i>Permit</i><strong>Window Start</strong><em>Late Permit Blocked</em></div><p>Only permits formed before the window can protect a change.</p></article><article><span>04 / SELF-SERVING EXCEPTION</span><h3>One party writes the incident story</h3><div className="mechanism-diagram evidence"><b>Provider Claim</b><b>Customer Claim</b><i>→ Frozen Evidence Policy →</i><strong>GenLayer Facts → Contract Consequence</strong></div><p>Evidence and code constrain both sides.</p></article></div></section>
  <section className="landing-section lifecycle-section"><div className="section-heading"><div><div className="kicker">ONE BONDED LIFECYCLE</div><h2>From Promise To Settlement.</h2></div><Link className="text-link" href="/protocol">Explore the protocol ↗</Link></div><div className="lifecycle-rail">{[["FORMATION","Bond covenant","create_covenant"],["ADMISSION","Request · gate · consensus","request_reservation · review_reservation"],["OPERATIONS","Preflight the change","propose_change · review_change"],["INCIDENT","Measure · examine · challenge","open_incident · examine_incident"],["SETTLEMENT","Calculate · finalize · withdraw","judge_liability · finalize_incident · withdraw_credit"]].map(([n,t,m],i)=><div className="lifecycle-step" key={n}><span>0{i+1} / {n}</span><b>{t}</b><code>{m}</code></div>)}</div></section>
  <section className="landing-section consensus-section"><div><div className="kicker">WHY GENLAYER</div><h2>Facts Need Consensus.<br/>Money Needs Rules.</h2><p>A deterministic contract compares timestamps and calculates overlap. GenLayer establishes the changing public facts that code cannot fairly infer alone.</p></div><div className="facts-money"><div><span>GENLAYER ESTABLISHES</span>{["Service Health","Measurement Validity","Causation","Clause Satisfaction","Evidence Conflicts"].map(x=><b key={x}>{x}</b>)}</div><div className="transfer"><strong>FACTS</strong><span>↓</span><strong>CONTRACT LAW</strong></div><div><span>CONTRACT CODE CALCULATES</span>{["Capacity","Collateral","Temporal Overlap","Liable BPS","Payout","Escrow Accounting"].map(x=><b key={x}>{x}</b>)}</div></div></section>
  <section className="landing-section evidence-section"><div className="section-heading"><div><div className="kicker">FROZEN AT COVENANT FORMATION</div><h2>Origin + Authorized Class = Evidence Candidate</h2></div></div><div className="evidence-model"><article className="evidence-stage"><span className="evidence-stage-number">01</span><h3>Register Origin</h3><p>HTTPS origin is frozen. Future paths may vary.</p></article><article className="evidence-stage"><span className="evidence-stage-number">02</span><h3>Authorize Class</h3><p>An origin may submit only its frozen evidence class.</p></article><article className="evidence-stage"><span className="evidence-stage-number">03</span><h3>Preserve Independence</h3><p>Duplicate origins do not count twice. A provider origin cannot impersonate an independent probe.</p></article><article className="evidence-stage"><span className="evidence-stage-number">04</span><h3>Consensus Reads Content</h3><p>Validators evaluate permitted evidence. Redirect provenance is not claimed when the runtime cannot expose it.</p></article></div></section>
  <section className="landing-section release-section"><div><div className="kicker">CANONICAL RELEASE</div><h2>Live On-Chain State</h2><p>Network: GenLayer Studionet · Chain 61999</p><p>Contract: <code>{CONTRACT_ADDRESS||"Not configured"}</code></p><p>Source: <code>add2f35d08cde554bec6d9bed98c5094554035d9</code></p><p>Accounting: <b>{stats?String(stats.accounting_balanced):"Read unavailable"}</b></p></div><a className="button ghost" href={CONTRACT_ADDRESS?`${EXPLORER}/address/${CONTRACT_ADDRESS}`:undefined}>View on Explorer ↗</a></section>
  <section className="final-cta"><div className="kicker">CONTROL THE EXPOSURE</div><h2>Control The Promise<br/>Before The Promise Controls You.</h2><div className="final-cta-actions"><Link className="button primary" href="/control">Enter Control Room</Link><Link className="button orange" href="/services/new">Bond a Service</Link><Link className="button ghost" href="/protocol">Read the Protocol</Link></div></section>
 </>;
 }
function Process({title,tone,items}:{title:string,tone:string,items:string[]}){return <div className={`flow-side ${tone}`}><span>{title}</span><div className="flow-stages">{items.map((item,i)=><div className="flow-stage" key={item}><b>0{i+1}</b><strong>{item}</strong></div>)}</div></div>}



function Instrument({title,rows}:{title:string,rows:string[][]}){return <div className="promise-surface instrument"><div className="surface-head"><span>{title}</span><span>MECHANICAL GATE</span></div><div className="instrument-rail"><i/><b>SAFE BOUNDARY</b></div><div className="surface-rows">{rows.map(([a,b],i)=><div className={i===rows.length-2?"incoming":""} key={a}><span>{a}</span><b>{b}</b></div>)}</div></div>}

